# This is a basic workflow to help you get started with Actions

name: publish cn docs

# Controls when the workflow will run
on:
  push:
    branches: [ "docs-cn" ]
  pull_request:
    branches: [ "docs-cn" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: 11
          distribution: temurin

      # Runs gradle command publish cn docs
      - name: Publish cn docs
        run: ./gradlew asciidoctor -P lang=cn
